channel_sources:
  - conda-forge/label/chemdyg_dev,conda-forge/label/e3sm_diags_dev,conda-forge/label/e3sm_to_cmip_dev,conda-forge/label/mache_dev,conda-forge/label/mpas_analysis_dev,conda-forge/label/mpas_tools_dev,conda-forge/label/zppy_dev,conda-forge/label/zppy_interfaces_dev,conda-forge/label/zstash_dev,conda-forge
channel_targets:
  - conda-forge e3sm_unified_dev
mpi:
  - nompi
  - openmpi
  - mpich
  - hpc
